version: '3.6'
services:
  db:
    image: postgis/postgis
    container_name: ev-charger-app-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - db_persdata:/var/lib/postgrespers
    networks:
      - backdb
    expose:
      - 5432

  backend:
    image: norberttalpos/ev-charger-app-backend:latest
    container_name: ev-charger-app-backend
    environment:
      WAIT_HOSTS: postgres:5432
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/db
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: postgres
      JWT_HEADER: Authorization
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.spatial.dialect.postgis.PostgisDialect
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ev.charger.app@gmail.com
      SPRING_MAIL_PASSWORD: jokerdes
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: smtp.gmail.com
    ports:
      - 8080:8080
      - 587:587
    depends_on:
      - db
    networks:
      - frontback
      - backdb

  frontend:
    image: norberttalpos/ev-charger-app-frontend:latest
    container_name: ev-charger-app-frontend
    ports:
      - 8081:8080
    depends_on:
      - backend
    networks:
      - frontback

networks:
  backdb:
    driver: bridge
  frontback:
    driver: bridge

volumes:
  db_persdata : {}
