name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run:
          mvn clean install -DskipTests --file pom.xml

      - uses: actions/checkout@v1

      - run: mkdir -p target/

      - run: echo hello > target/ev-charger-app-server.jar

      - uses: actions/upload-artifact@v1
        with:
          name: ev-charger-app-server
          path: target/

  docker:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: norberttalpos
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./src/frontend/ev-charger-app-client
          file: Dockerfile
          push: true
          tags: norberttalpos/ev-charger-app-frontend:latest

      - name: Build & push backend image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: norberttalpos/ev-charger-app-backend:latest