name: Docker Image CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run:
          mvn clean install -DskipTests --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: norberttalpos
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: actions/checkout@v2
        name: Check out code

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx for Frontend
        uses: docker/setup-buildx-action@v1
        id: frontend-builder

      - name: Set up Docker Buildx for Backend
        uses: docker/setup-buildx-action@v1
        id: backend-builder

      - name: Build & push backend image
        id: docker-build-backend
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          builder: ${{ steps.backend-builder.outputs.name }}
          push: true
          tags: norberttalpos/ev-charger-app-backend:latest

      - name: Build & push frontend image
        id: docker-build-frontend
        uses: docker/build-push-action@v2
        with:
          file: ./src/frontend/ev-charger-app-client/Dockerfile
          builder: ${{ steps.frontend-builder.outputs.name }}
          push: true
          tags: norberttalpos/ev-charger-app-frontend:latest